version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Expose port 3000 for the frontend
    environment:
      - VITE_BACKEND_URL=http://backend:5000  # Use VITE_ prefix for Vite
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://razzi:Razzi0984@cluster0.vuen418.mongodb.net/mlops
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
