apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2  # Adjust based on your needs
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mlops-assignment2-frontend:latest  # Updated image name
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer  # Change to NodePort if you want to expose it differently
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
